database:
  user: alpha
  password: alpha
  host: 127.0.0.1:3306
  name: practice
  maxIdleConnections: 5
  maxOpenConnections: 5
  maxConnectionLifetime: 50s
  maxConnectionIdletime: 50s
  disableTLS: true
  debug: true