database:
  user: shivam_kumar
  password: shivam123
  host: 127.0.0.1:3306
  name: GO_DB
  maxIdleConnections: 5
  maxOpenConnections: 5
  maxConnectionLifetime: 50s
  maxConnectionIdletime: 50s
  disableTLS: true
  debug: true

kafka:
  consumers:
    report:
      bootstrapServers:
        - 172.16.0.11:9092
      group: get-subs
      topic: get-subs-local
  producers:
    report:
      bootstrapServers: 
        - 172.16.0.11:9092
      topic: get-subs-local