// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/shivamk2406/Practice/graphql/graph"
	"github.com/shivamk2406/Practice/internal/service/user"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func initializedReg(db *gorm.DB) *graph.Resolver {
	userDB := user.NewRepo(db)
	resolver := graph.NewResolver(userDB)
	return resolver
}
