// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/shivamk2406/Practice/practice/datatypes/adapters/json"
	"github.com/shivamk2406/Practice/practice/datatypes/adapters/memcache"
	"github.com/shivamk2406/Practice/practice/datatypes/interfaces"
	"github.com/shivamk2406/Practice/practice/datatypes/service"
)

// Injectors from wire.go:

func initializedReg() interfaces.API {
	repository := json.NewUserActionJson()
	userActionCache := memcache.NewUserActionCache(repository)
	api := service.NewUserActionService(userActionCache)
	return api
}
