// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package graphl_schema

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

// GetConfigGetTenantByDomainTenant includes the requested fields of the GraphQL type Tenant.
type GetConfigGetTenantByDomainTenant struct {
	Name           string                                                     `json:"name"`
	Id             string                                                     `json:"id"`
	RedirectURI    string                                                     `json:"redirectURI"`
	ConfigAttr     GetConfigGetTenantByDomainTenantConfigAttrConfigAttributes `json:"configAttr"`
	Country        GetConfigGetTenantByDomainTenantCountry                    `json:"country"`
	CheckoutConfig GetConfigGetTenantByDomainTenantCheckoutConfig             `json:"checkoutConfig"`
}

// GetName returns GetConfigGetTenantByDomainTenant.Name, and is useful for accessing the field via an interface.
func (v *GetConfigGetTenantByDomainTenant) GetName() string { return v.Name }

// GetId returns GetConfigGetTenantByDomainTenant.Id, and is useful for accessing the field via an interface.
func (v *GetConfigGetTenantByDomainTenant) GetId() string { return v.Id }

// GetRedirectURI returns GetConfigGetTenantByDomainTenant.RedirectURI, and is useful for accessing the field via an interface.
func (v *GetConfigGetTenantByDomainTenant) GetRedirectURI() string { return v.RedirectURI }

// GetConfigAttr returns GetConfigGetTenantByDomainTenant.ConfigAttr, and is useful for accessing the field via an interface.
func (v *GetConfigGetTenantByDomainTenant) GetConfigAttr() GetConfigGetTenantByDomainTenantConfigAttrConfigAttributes {
	return v.ConfigAttr
}

// GetCountry returns GetConfigGetTenantByDomainTenant.Country, and is useful for accessing the field via an interface.
func (v *GetConfigGetTenantByDomainTenant) GetCountry() GetConfigGetTenantByDomainTenantCountry {
	return v.Country
}

// GetCheckoutConfig returns GetConfigGetTenantByDomainTenant.CheckoutConfig, and is useful for accessing the field via an interface.
func (v *GetConfigGetTenantByDomainTenant) GetCheckoutConfig() GetConfigGetTenantByDomainTenantCheckoutConfig {
	return v.CheckoutConfig
}

// GetConfigGetTenantByDomainTenantCheckoutConfig includes the requested fields of the GraphQL type CheckoutConfig.
type GetConfigGetTenantByDomainTenantCheckoutConfig struct {
	Payment_provider GetConfigGetTenantByDomainTenantCheckoutConfigPayment_providerPaymentProvider `json:"payment_provider"`
}

// GetPayment_provider returns GetConfigGetTenantByDomainTenantCheckoutConfig.Payment_provider, and is useful for accessing the field via an interface.
func (v *GetConfigGetTenantByDomainTenantCheckoutConfig) GetPayment_provider() GetConfigGetTenantByDomainTenantCheckoutConfigPayment_providerPaymentProvider {
	return v.Payment_provider
}

// GetConfigGetTenantByDomainTenantCheckoutConfigPayment_providerPaymentProvider includes the requested fields of the GraphQL type PaymentProvider.
type GetConfigGetTenantByDomainTenantCheckoutConfigPayment_providerPaymentProvider struct {
	Payment_model string `json:"payment_model"`
	Set_mandate   bool   `json:"set_mandate"`
}

// GetPayment_model returns GetConfigGetTenantByDomainTenantCheckoutConfigPayment_providerPaymentProvider.Payment_model, and is useful for accessing the field via an interface.
func (v *GetConfigGetTenantByDomainTenantCheckoutConfigPayment_providerPaymentProvider) GetPayment_model() string {
	return v.Payment_model
}

// GetSet_mandate returns GetConfigGetTenantByDomainTenantCheckoutConfigPayment_providerPaymentProvider.Set_mandate, and is useful for accessing the field via an interface.
func (v *GetConfigGetTenantByDomainTenantCheckoutConfigPayment_providerPaymentProvider) GetSet_mandate() bool {
	return v.Set_mandate
}

// GetConfigGetTenantByDomainTenantConfigAttrConfigAttributes includes the requested fields of the GraphQL type ConfigAttributes.
type GetConfigGetTenantByDomainTenantConfigAttrConfigAttributes struct {
	Tenant_id                 string                                                                                      `json:"tenant_id"`
	Analytics_project_id      string                                                                                      `json:"analytics_project_id"`
	Image_base_uri            string                                                                                      `json:"image_base_uri"`
	Partner_title             string                                                                                      `json:"partner_title"`
	Locale                    string                                                                                      `json:"locale"`
	Support_email             string                                                                                      `json:"support_email"`
	Browser_tab_icon_uri      string                                                                                      `json:"browser_tab_icon_uri"`
	Browser_tab_title         string                                                                                      `json:"browser_tab_title"`
	Theme_data                []GetConfigGetTenantByDomainTenantConfigAttrConfigAttributesTheme_dataMapItem               `json:"theme_data"`
	Home_screen_banner        GetConfigGetTenantByDomainTenantConfigAttrConfigAttributesHome_screen_bannerBanner          `json:"home_screen_banner"`
	Onboarding_banners        []GetConfigGetTenantByDomainTenantConfigAttrConfigAttributesOnboarding_bannersBanner        `json:"onboarding_banners"`
	Mobile_onboarding_banners []GetConfigGetTenantByDomainTenantConfigAttrConfigAttributesMobile_onboarding_bannersBanner `json:"mobile_onboarding_banners"`
	Enable_country_code       []string                                                                                    `json:"enable_country_code"`
}

// GetTenant_id returns GetConfigGetTenantByDomainTenantConfigAttrConfigAttributes.Tenant_id, and is useful for accessing the field via an interface.
func (v *GetConfigGetTenantByDomainTenantConfigAttrConfigAttributes) GetTenant_id() string {
	return v.Tenant_id
}

// GetAnalytics_project_id returns GetConfigGetTenantByDomainTenantConfigAttrConfigAttributes.Analytics_project_id, and is useful for accessing the field via an interface.
func (v *GetConfigGetTenantByDomainTenantConfigAttrConfigAttributes) GetAnalytics_project_id() string {
	return v.Analytics_project_id
}

// GetImage_base_uri returns GetConfigGetTenantByDomainTenantConfigAttrConfigAttributes.Image_base_uri, and is useful for accessing the field via an interface.
func (v *GetConfigGetTenantByDomainTenantConfigAttrConfigAttributes) GetImage_base_uri() string {
	return v.Image_base_uri
}

// GetPartner_title returns GetConfigGetTenantByDomainTenantConfigAttrConfigAttributes.Partner_title, and is useful for accessing the field via an interface.
func (v *GetConfigGetTenantByDomainTenantConfigAttrConfigAttributes) GetPartner_title() string {
	return v.Partner_title
}

// GetLocale returns GetConfigGetTenantByDomainTenantConfigAttrConfigAttributes.Locale, and is useful for accessing the field via an interface.
func (v *GetConfigGetTenantByDomainTenantConfigAttrConfigAttributes) GetLocale() string {
	return v.Locale
}

// GetSupport_email returns GetConfigGetTenantByDomainTenantConfigAttrConfigAttributes.Support_email, and is useful for accessing the field via an interface.
func (v *GetConfigGetTenantByDomainTenantConfigAttrConfigAttributes) GetSupport_email() string {
	return v.Support_email
}

// GetBrowser_tab_icon_uri returns GetConfigGetTenantByDomainTenantConfigAttrConfigAttributes.Browser_tab_icon_uri, and is useful for accessing the field via an interface.
func (v *GetConfigGetTenantByDomainTenantConfigAttrConfigAttributes) GetBrowser_tab_icon_uri() string {
	return v.Browser_tab_icon_uri
}

// GetBrowser_tab_title returns GetConfigGetTenantByDomainTenantConfigAttrConfigAttributes.Browser_tab_title, and is useful for accessing the field via an interface.
func (v *GetConfigGetTenantByDomainTenantConfigAttrConfigAttributes) GetBrowser_tab_title() string {
	return v.Browser_tab_title
}

// GetTheme_data returns GetConfigGetTenantByDomainTenantConfigAttrConfigAttributes.Theme_data, and is useful for accessing the field via an interface.
func (v *GetConfigGetTenantByDomainTenantConfigAttrConfigAttributes) GetTheme_data() []GetConfigGetTenantByDomainTenantConfigAttrConfigAttributesTheme_dataMapItem {
	return v.Theme_data
}

// GetHome_screen_banner returns GetConfigGetTenantByDomainTenantConfigAttrConfigAttributes.Home_screen_banner, and is useful for accessing the field via an interface.
func (v *GetConfigGetTenantByDomainTenantConfigAttrConfigAttributes) GetHome_screen_banner() GetConfigGetTenantByDomainTenantConfigAttrConfigAttributesHome_screen_bannerBanner {
	return v.Home_screen_banner
}

// GetOnboarding_banners returns GetConfigGetTenantByDomainTenantConfigAttrConfigAttributes.Onboarding_banners, and is useful for accessing the field via an interface.
func (v *GetConfigGetTenantByDomainTenantConfigAttrConfigAttributes) GetOnboarding_banners() []GetConfigGetTenantByDomainTenantConfigAttrConfigAttributesOnboarding_bannersBanner {
	return v.Onboarding_banners
}

// GetMobile_onboarding_banners returns GetConfigGetTenantByDomainTenantConfigAttrConfigAttributes.Mobile_onboarding_banners, and is useful for accessing the field via an interface.
func (v *GetConfigGetTenantByDomainTenantConfigAttrConfigAttributes) GetMobile_onboarding_banners() []GetConfigGetTenantByDomainTenantConfigAttrConfigAttributesMobile_onboarding_bannersBanner {
	return v.Mobile_onboarding_banners
}

// GetEnable_country_code returns GetConfigGetTenantByDomainTenantConfigAttrConfigAttributes.Enable_country_code, and is useful for accessing the field via an interface.
func (v *GetConfigGetTenantByDomainTenantConfigAttrConfigAttributes) GetEnable_country_code() []string {
	return v.Enable_country_code
}

// GetConfigGetTenantByDomainTenantConfigAttrConfigAttributesHome_screen_bannerBanner includes the requested fields of the GraphQL type Banner.
type GetConfigGetTenantByDomainTenantConfigAttrConfigAttributesHome_screen_bannerBanner struct {
	Title       string `json:"title"`
	Subtitle    string `json:"subtitle"`
	Description string `json:"description"`
	Image_uri   string `json:"image_uri"`
}

// GetTitle returns GetConfigGetTenantByDomainTenantConfigAttrConfigAttributesHome_screen_bannerBanner.Title, and is useful for accessing the field via an interface.
func (v *GetConfigGetTenantByDomainTenantConfigAttrConfigAttributesHome_screen_bannerBanner) GetTitle() string {
	return v.Title
}

// GetSubtitle returns GetConfigGetTenantByDomainTenantConfigAttrConfigAttributesHome_screen_bannerBanner.Subtitle, and is useful for accessing the field via an interface.
func (v *GetConfigGetTenantByDomainTenantConfigAttrConfigAttributesHome_screen_bannerBanner) GetSubtitle() string {
	return v.Subtitle
}

// GetDescription returns GetConfigGetTenantByDomainTenantConfigAttrConfigAttributesHome_screen_bannerBanner.Description, and is useful for accessing the field via an interface.
func (v *GetConfigGetTenantByDomainTenantConfigAttrConfigAttributesHome_screen_bannerBanner) GetDescription() string {
	return v.Description
}

// GetImage_uri returns GetConfigGetTenantByDomainTenantConfigAttrConfigAttributesHome_screen_bannerBanner.Image_uri, and is useful for accessing the field via an interface.
func (v *GetConfigGetTenantByDomainTenantConfigAttrConfigAttributesHome_screen_bannerBanner) GetImage_uri() string {
	return v.Image_uri
}

// GetConfigGetTenantByDomainTenantConfigAttrConfigAttributesMobile_onboarding_bannersBanner includes the requested fields of the GraphQL type Banner.
type GetConfigGetTenantByDomainTenantConfigAttrConfigAttributesMobile_onboarding_bannersBanner struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	Image_uri   string `json:"image_uri"`
}

// GetTitle returns GetConfigGetTenantByDomainTenantConfigAttrConfigAttributesMobile_onboarding_bannersBanner.Title, and is useful for accessing the field via an interface.
func (v *GetConfigGetTenantByDomainTenantConfigAttrConfigAttributesMobile_onboarding_bannersBanner) GetTitle() string {
	return v.Title
}

// GetDescription returns GetConfigGetTenantByDomainTenantConfigAttrConfigAttributesMobile_onboarding_bannersBanner.Description, and is useful for accessing the field via an interface.
func (v *GetConfigGetTenantByDomainTenantConfigAttrConfigAttributesMobile_onboarding_bannersBanner) GetDescription() string {
	return v.Description
}

// GetImage_uri returns GetConfigGetTenantByDomainTenantConfigAttrConfigAttributesMobile_onboarding_bannersBanner.Image_uri, and is useful for accessing the field via an interface.
func (v *GetConfigGetTenantByDomainTenantConfigAttrConfigAttributesMobile_onboarding_bannersBanner) GetImage_uri() string {
	return v.Image_uri
}

// GetConfigGetTenantByDomainTenantConfigAttrConfigAttributesOnboarding_bannersBanner includes the requested fields of the GraphQL type Banner.
type GetConfigGetTenantByDomainTenantConfigAttrConfigAttributesOnboarding_bannersBanner struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	Image_uri   string `json:"image_uri"`
}

// GetTitle returns GetConfigGetTenantByDomainTenantConfigAttrConfigAttributesOnboarding_bannersBanner.Title, and is useful for accessing the field via an interface.
func (v *GetConfigGetTenantByDomainTenantConfigAttrConfigAttributesOnboarding_bannersBanner) GetTitle() string {
	return v.Title
}

// GetDescription returns GetConfigGetTenantByDomainTenantConfigAttrConfigAttributesOnboarding_bannersBanner.Description, and is useful for accessing the field via an interface.
func (v *GetConfigGetTenantByDomainTenantConfigAttrConfigAttributesOnboarding_bannersBanner) GetDescription() string {
	return v.Description
}

// GetImage_uri returns GetConfigGetTenantByDomainTenantConfigAttrConfigAttributesOnboarding_bannersBanner.Image_uri, and is useful for accessing the field via an interface.
func (v *GetConfigGetTenantByDomainTenantConfigAttrConfigAttributesOnboarding_bannersBanner) GetImage_uri() string {
	return v.Image_uri
}

// GetConfigGetTenantByDomainTenantConfigAttrConfigAttributesTheme_dataMapItem includes the requested fields of the GraphQL type MapItem.
type GetConfigGetTenantByDomainTenantConfigAttrConfigAttributesTheme_dataMapItem struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

// GetKey returns GetConfigGetTenantByDomainTenantConfigAttrConfigAttributesTheme_dataMapItem.Key, and is useful for accessing the field via an interface.
func (v *GetConfigGetTenantByDomainTenantConfigAttrConfigAttributesTheme_dataMapItem) GetKey() string {
	return v.Key
}

// GetValue returns GetConfigGetTenantByDomainTenantConfigAttrConfigAttributesTheme_dataMapItem.Value, and is useful for accessing the field via an interface.
func (v *GetConfigGetTenantByDomainTenantConfigAttrConfigAttributesTheme_dataMapItem) GetValue() string {
	return v.Value
}

// GetConfigGetTenantByDomainTenantCountry includes the requested fields of the GraphQL type Country.
type GetConfigGetTenantByDomainTenantCountry struct {
	CountryCode string `json:"countryCode"`
}

// GetCountryCode returns GetConfigGetTenantByDomainTenantCountry.CountryCode, and is useful for accessing the field via an interface.
func (v *GetConfigGetTenantByDomainTenantCountry) GetCountryCode() string { return v.CountryCode }

// GetConfigResponse is returned by GetConfig on success.
type GetConfigResponse struct {
	GetTenantByDomain GetConfigGetTenantByDomainTenant `json:"GetTenantByDomain"`
}

// GetGetTenantByDomain returns GetConfigResponse.GetTenantByDomain, and is useful for accessing the field via an interface.
func (v *GetConfigResponse) GetGetTenantByDomain() GetConfigGetTenantByDomainTenant {
	return v.GetTenantByDomain
}

// GetCountryByIsdCodeGetCountryByIsdCodeCountry includes the requested fields of the GraphQL type Country.
type GetCountryByIsdCodeGetCountryByIsdCodeCountry struct {
	Name                  string `json:"name"`
	FullName              string `json:"fullName"`
	CurrencySymbol        string `json:"currencySymbol"`
	CountryCode           string `json:"countryCode"`
	CurrencyCode          string `json:"currencyCode"`
	CurrencyName          string `json:"currencyName"`
	IsdCode               string `json:"isdCode"`
	CurrencyDecimals      int    `json:"currencyDecimals"`
	FlagLogo              string `json:"flagLogo"`
	MobileValidationRegex string `json:"mobileValidationRegex"`
}

// GetName returns GetCountryByIsdCodeGetCountryByIsdCodeCountry.Name, and is useful for accessing the field via an interface.
func (v *GetCountryByIsdCodeGetCountryByIsdCodeCountry) GetName() string { return v.Name }

// GetFullName returns GetCountryByIsdCodeGetCountryByIsdCodeCountry.FullName, and is useful for accessing the field via an interface.
func (v *GetCountryByIsdCodeGetCountryByIsdCodeCountry) GetFullName() string { return v.FullName }

// GetCurrencySymbol returns GetCountryByIsdCodeGetCountryByIsdCodeCountry.CurrencySymbol, and is useful for accessing the field via an interface.
func (v *GetCountryByIsdCodeGetCountryByIsdCodeCountry) GetCurrencySymbol() string {
	return v.CurrencySymbol
}

// GetCountryCode returns GetCountryByIsdCodeGetCountryByIsdCodeCountry.CountryCode, and is useful for accessing the field via an interface.
func (v *GetCountryByIsdCodeGetCountryByIsdCodeCountry) GetCountryCode() string { return v.CountryCode }

// GetCurrencyCode returns GetCountryByIsdCodeGetCountryByIsdCodeCountry.CurrencyCode, and is useful for accessing the field via an interface.
func (v *GetCountryByIsdCodeGetCountryByIsdCodeCountry) GetCurrencyCode() string {
	return v.CurrencyCode
}

// GetCurrencyName returns GetCountryByIsdCodeGetCountryByIsdCodeCountry.CurrencyName, and is useful for accessing the field via an interface.
func (v *GetCountryByIsdCodeGetCountryByIsdCodeCountry) GetCurrencyName() string {
	return v.CurrencyName
}

// GetIsdCode returns GetCountryByIsdCodeGetCountryByIsdCodeCountry.IsdCode, and is useful for accessing the field via an interface.
func (v *GetCountryByIsdCodeGetCountryByIsdCodeCountry) GetIsdCode() string { return v.IsdCode }

// GetCurrencyDecimals returns GetCountryByIsdCodeGetCountryByIsdCodeCountry.CurrencyDecimals, and is useful for accessing the field via an interface.
func (v *GetCountryByIsdCodeGetCountryByIsdCodeCountry) GetCurrencyDecimals() int {
	return v.CurrencyDecimals
}

// GetFlagLogo returns GetCountryByIsdCodeGetCountryByIsdCodeCountry.FlagLogo, and is useful for accessing the field via an interface.
func (v *GetCountryByIsdCodeGetCountryByIsdCodeCountry) GetFlagLogo() string { return v.FlagLogo }

// GetMobileValidationRegex returns GetCountryByIsdCodeGetCountryByIsdCodeCountry.MobileValidationRegex, and is useful for accessing the field via an interface.
func (v *GetCountryByIsdCodeGetCountryByIsdCodeCountry) GetMobileValidationRegex() string {
	return v.MobileValidationRegex
}

// GetCountryByIsdCodeResponse is returned by GetCountryByIsdCode on success.
type GetCountryByIsdCodeResponse struct {
	GetCountryByIsdCode GetCountryByIsdCodeGetCountryByIsdCodeCountry `json:"GetCountryByIsdCode"`
}

// GetGetCountryByIsdCode returns GetCountryByIsdCodeResponse.GetCountryByIsdCode, and is useful for accessing the field via an interface.
func (v *GetCountryByIsdCodeResponse) GetGetCountryByIsdCode() GetCountryByIsdCodeGetCountryByIsdCodeCountry {
	return v.GetCountryByIsdCode
}

// GetStatesByCountryCodeGetStatesByCountryCodeState includes the requested fields of the GraphQL type State.
type GetStatesByCountryCodeGetStatesByCountryCodeState struct {
	Id        int    `json:"id"`
	StateName string `json:"stateName"`
}

// GetId returns GetStatesByCountryCodeGetStatesByCountryCodeState.Id, and is useful for accessing the field via an interface.
func (v *GetStatesByCountryCodeGetStatesByCountryCodeState) GetId() int { return v.Id }

// GetStateName returns GetStatesByCountryCodeGetStatesByCountryCodeState.StateName, and is useful for accessing the field via an interface.
func (v *GetStatesByCountryCodeGetStatesByCountryCodeState) GetStateName() string { return v.StateName }

// GetStatesByCountryCodeResponse is returned by GetStatesByCountryCode on success.
type GetStatesByCountryCodeResponse struct {
	GetStatesByCountryCode []GetStatesByCountryCodeGetStatesByCountryCodeState `json:"GetStatesByCountryCode"`
}

// GetGetStatesByCountryCode returns GetStatesByCountryCodeResponse.GetStatesByCountryCode, and is useful for accessing the field via an interface.
func (v *GetStatesByCountryCodeResponse) GetGetStatesByCountryCode() []GetStatesByCountryCodeGetStatesByCountryCodeState {
	return v.GetStatesByCountryCode
}

// GetTenantByIdGetTenant includes the requested fields of the GraphQL type Tenant.
type GetTenantByIdGetTenant struct {
	Id                string                                                       `json:"id"`
	Recordid          string                                                       `json:"recordid"`
	ChannelName       string                                                       `json:"channelName"`
	Title             string                                                       `json:"title"`
	DisplayName       string                                                       `json:"displayName"`
	Domain            string                                                       `json:"domain"`
	PaymentURI        string                                                       `json:"paymentURI"`
	SupportEmail      string                                                       `json:"supportEmail"`
	Country           GetTenantByIdGetTenantCountry                                `json:"country"`
	NotificationAttr  GetTenantByIdGetTenantNotificationAttrNotificationAttributes `json:"notificationAttr"`
	SupportAttributes GetTenantByIdGetTenantSupportAttributes                      `json:"supportAttributes"`
	CheckoutConfig    GetTenantByIdGetTenantCheckoutConfig                         `json:"checkoutConfig"`
}

// GetId returns GetTenantByIdGetTenant.Id, and is useful for accessing the field via an interface.
func (v *GetTenantByIdGetTenant) GetId() string { return v.Id }

// GetRecordid returns GetTenantByIdGetTenant.Recordid, and is useful for accessing the field via an interface.
func (v *GetTenantByIdGetTenant) GetRecordid() string { return v.Recordid }

// GetChannelName returns GetTenantByIdGetTenant.ChannelName, and is useful for accessing the field via an interface.
func (v *GetTenantByIdGetTenant) GetChannelName() string { return v.ChannelName }

// GetTitle returns GetTenantByIdGetTenant.Title, and is useful for accessing the field via an interface.
func (v *GetTenantByIdGetTenant) GetTitle() string { return v.Title }

// GetDisplayName returns GetTenantByIdGetTenant.DisplayName, and is useful for accessing the field via an interface.
func (v *GetTenantByIdGetTenant) GetDisplayName() string { return v.DisplayName }

// GetDomain returns GetTenantByIdGetTenant.Domain, and is useful for accessing the field via an interface.
func (v *GetTenantByIdGetTenant) GetDomain() string { return v.Domain }

// GetPaymentURI returns GetTenantByIdGetTenant.PaymentURI, and is useful for accessing the field via an interface.
func (v *GetTenantByIdGetTenant) GetPaymentURI() string { return v.PaymentURI }

// GetSupportEmail returns GetTenantByIdGetTenant.SupportEmail, and is useful for accessing the field via an interface.
func (v *GetTenantByIdGetTenant) GetSupportEmail() string { return v.SupportEmail }

// GetCountry returns GetTenantByIdGetTenant.Country, and is useful for accessing the field via an interface.
func (v *GetTenantByIdGetTenant) GetCountry() GetTenantByIdGetTenantCountry { return v.Country }

// GetNotificationAttr returns GetTenantByIdGetTenant.NotificationAttr, and is useful for accessing the field via an interface.
func (v *GetTenantByIdGetTenant) GetNotificationAttr() GetTenantByIdGetTenantNotificationAttrNotificationAttributes {
	return v.NotificationAttr
}

// GetSupportAttributes returns GetTenantByIdGetTenant.SupportAttributes, and is useful for accessing the field via an interface.
func (v *GetTenantByIdGetTenant) GetSupportAttributes() GetTenantByIdGetTenantSupportAttributes {
	return v.SupportAttributes
}

// GetCheckoutConfig returns GetTenantByIdGetTenant.CheckoutConfig, and is useful for accessing the field via an interface.
func (v *GetTenantByIdGetTenant) GetCheckoutConfig() GetTenantByIdGetTenantCheckoutConfig {
	return v.CheckoutConfig
}

// GetTenantByIdGetTenantCheckoutConfig includes the requested fields of the GraphQL type CheckoutConfig.
type GetTenantByIdGetTenantCheckoutConfig struct {
	Payment_provider GetTenantByIdGetTenantCheckoutConfigPayment_providerPaymentProvider `json:"payment_provider"`
}

// GetPayment_provider returns GetTenantByIdGetTenantCheckoutConfig.Payment_provider, and is useful for accessing the field via an interface.
func (v *GetTenantByIdGetTenantCheckoutConfig) GetPayment_provider() GetTenantByIdGetTenantCheckoutConfigPayment_providerPaymentProvider {
	return v.Payment_provider
}

// GetTenantByIdGetTenantCheckoutConfigPayment_providerPaymentProvider includes the requested fields of the GraphQL type PaymentProvider.
type GetTenantByIdGetTenantCheckoutConfigPayment_providerPaymentProvider struct {
	Set_mandate          bool   `json:"set_mandate"`
	Payment_model        string `json:"payment_model"`
	Payment_gateway_id   string `json:"payment_gateway_id"`
	Payment_gateway_type string `json:"payment_gateway_type"`
}

// GetSet_mandate returns GetTenantByIdGetTenantCheckoutConfigPayment_providerPaymentProvider.Set_mandate, and is useful for accessing the field via an interface.
func (v *GetTenantByIdGetTenantCheckoutConfigPayment_providerPaymentProvider) GetSet_mandate() bool {
	return v.Set_mandate
}

// GetPayment_model returns GetTenantByIdGetTenantCheckoutConfigPayment_providerPaymentProvider.Payment_model, and is useful for accessing the field via an interface.
func (v *GetTenantByIdGetTenantCheckoutConfigPayment_providerPaymentProvider) GetPayment_model() string {
	return v.Payment_model
}

// GetPayment_gateway_id returns GetTenantByIdGetTenantCheckoutConfigPayment_providerPaymentProvider.Payment_gateway_id, and is useful for accessing the field via an interface.
func (v *GetTenantByIdGetTenantCheckoutConfigPayment_providerPaymentProvider) GetPayment_gateway_id() string {
	return v.Payment_gateway_id
}

// GetPayment_gateway_type returns GetTenantByIdGetTenantCheckoutConfigPayment_providerPaymentProvider.Payment_gateway_type, and is useful for accessing the field via an interface.
func (v *GetTenantByIdGetTenantCheckoutConfigPayment_providerPaymentProvider) GetPayment_gateway_type() string {
	return v.Payment_gateway_type
}

// GetTenantByIdGetTenantCountry includes the requested fields of the GraphQL type Country.
type GetTenantByIdGetTenantCountry struct {
	CountryCode string `json:"countryCode"`
}

// GetCountryCode returns GetTenantByIdGetTenantCountry.CountryCode, and is useful for accessing the field via an interface.
func (v *GetTenantByIdGetTenantCountry) GetCountryCode() string { return v.CountryCode }

// GetTenantByIdGetTenantNotificationAttrNotificationAttributes includes the requested fields of the GraphQL type NotificationAttributes.
type GetTenantByIdGetTenantNotificationAttrNotificationAttributes struct {
	RefundComment string `json:"refundComment"`
}

// GetRefundComment returns GetTenantByIdGetTenantNotificationAttrNotificationAttributes.RefundComment, and is useful for accessing the field via an interface.
func (v *GetTenantByIdGetTenantNotificationAttrNotificationAttributes) GetRefundComment() string {
	return v.RefundComment
}

// GetTenantByIdGetTenantSupportAttributes includes the requested fields of the GraphQL type SupportAttributes.
type GetTenantByIdGetTenantSupportAttributes struct {
	TicketTagId string `json:"ticketTagId"`
}

// GetTicketTagId returns GetTenantByIdGetTenantSupportAttributes.TicketTagId, and is useful for accessing the field via an interface.
func (v *GetTenantByIdGetTenantSupportAttributes) GetTicketTagId() string { return v.TicketTagId }

// GetTenantByIdResponse is returned by GetTenantById on success.
type GetTenantByIdResponse struct {
	GetTenant GetTenantByIdGetTenant `json:"GetTenant"`
}

// GetGetTenant returns GetTenantByIdResponse.GetTenant, and is useful for accessing the field via an interface.
func (v *GetTenantByIdResponse) GetGetTenant() GetTenantByIdGetTenant { return v.GetTenant }

// ListCountryListCountry includes the requested fields of the GraphQL type Country.
type ListCountryListCountry struct {
	Name                  string `json:"name"`
	FullName              string `json:"fullName"`
	CurrencySymbol        string `json:"currencySymbol"`
	CountryCode           string `json:"countryCode"`
	CurrencyCode          string `json:"currencyCode"`
	CurrencyName          string `json:"currencyName"`
	IsdCode               string `json:"isdCode"`
	CurrencyDecimals      int    `json:"currencyDecimals"`
	FlagLogo              string `json:"flagLogo"`
	MobileValidationRegex string `json:"mobileValidationRegex"`
}

// GetName returns ListCountryListCountry.Name, and is useful for accessing the field via an interface.
func (v *ListCountryListCountry) GetName() string { return v.Name }

// GetFullName returns ListCountryListCountry.FullName, and is useful for accessing the field via an interface.
func (v *ListCountryListCountry) GetFullName() string { return v.FullName }

// GetCurrencySymbol returns ListCountryListCountry.CurrencySymbol, and is useful for accessing the field via an interface.
func (v *ListCountryListCountry) GetCurrencySymbol() string { return v.CurrencySymbol }

// GetCountryCode returns ListCountryListCountry.CountryCode, and is useful for accessing the field via an interface.
func (v *ListCountryListCountry) GetCountryCode() string { return v.CountryCode }

// GetCurrencyCode returns ListCountryListCountry.CurrencyCode, and is useful for accessing the field via an interface.
func (v *ListCountryListCountry) GetCurrencyCode() string { return v.CurrencyCode }

// GetCurrencyName returns ListCountryListCountry.CurrencyName, and is useful for accessing the field via an interface.
func (v *ListCountryListCountry) GetCurrencyName() string { return v.CurrencyName }

// GetIsdCode returns ListCountryListCountry.IsdCode, and is useful for accessing the field via an interface.
func (v *ListCountryListCountry) GetIsdCode() string { return v.IsdCode }

// GetCurrencyDecimals returns ListCountryListCountry.CurrencyDecimals, and is useful for accessing the field via an interface.
func (v *ListCountryListCountry) GetCurrencyDecimals() int { return v.CurrencyDecimals }

// GetFlagLogo returns ListCountryListCountry.FlagLogo, and is useful for accessing the field via an interface.
func (v *ListCountryListCountry) GetFlagLogo() string { return v.FlagLogo }

// GetMobileValidationRegex returns ListCountryListCountry.MobileValidationRegex, and is useful for accessing the field via an interface.
func (v *ListCountryListCountry) GetMobileValidationRegex() string { return v.MobileValidationRegex }

// ListCountryResponse is returned by ListCountry on success.
type ListCountryResponse struct {
	ListCountry []ListCountryListCountry `json:"ListCountry"`
}

// GetListCountry returns ListCountryResponse.ListCountry, and is useful for accessing the field via an interface.
func (v *ListCountryResponse) GetListCountry() []ListCountryListCountry { return v.ListCountry }

// __GetConfigInput is used internally by genqlient
type __GetConfigInput struct {
	Input string `json:"input"`
}

// GetInput returns __GetConfigInput.Input, and is useful for accessing the field via an interface.
func (v *__GetConfigInput) GetInput() string { return v.Input }

// __GetCountryByIsdCodeInput is used internally by genqlient
type __GetCountryByIsdCodeInput struct {
	Input string `json:"input"`
}

// GetInput returns __GetCountryByIsdCodeInput.Input, and is useful for accessing the field via an interface.
func (v *__GetCountryByIsdCodeInput) GetInput() string { return v.Input }

// __GetStatesByCountryCodeInput is used internally by genqlient
type __GetStatesByCountryCodeInput struct {
	Input string `json:"input"`
}

// GetInput returns __GetStatesByCountryCodeInput.Input, and is useful for accessing the field via an interface.
func (v *__GetStatesByCountryCodeInput) GetInput() string { return v.Input }

// __GetTenantByIdInput is used internally by genqlient
type __GetTenantByIdInput struct {
	Input string `json:"input"`
}

// GetInput returns __GetTenantByIdInput.Input, and is useful for accessing the field via an interface.
func (v *__GetTenantByIdInput) GetInput() string { return v.Input }

func GetConfig(
	ctx context.Context,
	client graphql.Client,
	input string,
) (*GetConfigResponse, error) {
	req := &graphql.Request{
		OpName: "GetConfig",
		Query: `
query GetConfig ($input: String!) {
	GetTenantByDomain(domain: $input) {
		name
		id
		redirectURI
		configAttr {
			tenant_id
			analytics_project_id
			image_base_uri
			partner_title
			locale
			support_email
			browser_tab_icon_uri
			browser_tab_title
			theme_data {
				key
				value
			}
			home_screen_banner {
				title
				subtitle
				description
				image_uri
			}
			onboarding_banners {
				title
				description
				image_uri
			}
			mobile_onboarding_banners {
				title
				description
				image_uri
			}
			enable_country_code
		}
		country {
			countryCode
		}
		checkoutConfig {
			payment_provider {
				payment_model
				set_mandate
			}
		}
	}
}
`,
		Variables: &__GetConfigInput{
			Input: input,
		},
	}
	var err error

	var data GetConfigResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

func GetCountryByIsdCode(
	ctx context.Context,
	client graphql.Client,
	input string,
) (*GetCountryByIsdCodeResponse, error) {
	req := &graphql.Request{
		OpName: "GetCountryByIsdCode",
		Query: `
query GetCountryByIsdCode ($input: String!) {
	GetCountryByIsdCode(isdCode: $input) {
		name
		fullName
		currencySymbol
		countryCode
		currencyCode
		currencyName
		isdCode
		currencyDecimals
		flagLogo
		mobileValidationRegex
	}
}
`,
		Variables: &__GetCountryByIsdCodeInput{
			Input: input,
		},
	}
	var err error

	var data GetCountryByIsdCodeResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

func GetStatesByCountryCode(
	ctx context.Context,
	client graphql.Client,
	input string,
) (*GetStatesByCountryCodeResponse, error) {
	req := &graphql.Request{
		OpName: "GetStatesByCountryCode",
		Query: `
query GetStatesByCountryCode ($input: String!) {
	GetStatesByCountryCode(countryCode: $input) {
		id
		stateName
	}
}
`,
		Variables: &__GetStatesByCountryCodeInput{
			Input: input,
		},
	}
	var err error

	var data GetStatesByCountryCodeResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

func GetTenantById(
	ctx context.Context,
	client graphql.Client,
	input string,
) (*GetTenantByIdResponse, error) {
	req := &graphql.Request{
		OpName: "GetTenantById",
		Query: `
query GetTenantById ($input: ID!) {
	GetTenant(id: $input) {
		id
		recordid
		channelName
		title
		displayName
		domain
		paymentURI
		supportEmail
		country {
			countryCode
		}
		notificationAttr {
			refundComment
		}
		supportAttributes {
			ticketTagId
		}
		checkoutConfig {
			payment_provider {
				set_mandate
				payment_model
				payment_gateway_id
				payment_gateway_type
			}
		}
	}
}
`,
		Variables: &__GetTenantByIdInput{
			Input: input,
		},
	}
	var err error

	var data GetTenantByIdResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

func ListCountry(
	ctx context.Context,
	client graphql.Client,
) (*ListCountryResponse, error) {
	req := &graphql.Request{
		OpName: "ListCountry",
		Query: `
query ListCountry {
	ListCountry {
		name
		fullName
		currencySymbol
		countryCode
		currencyCode
		currencyName
		isdCode
		currencyDecimals
		flagLogo
		mobileValidationRegex
	}
}
`,
	}
	var err error

	var data ListCountryResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}
